/**:
  ros__parameters:
    use_sim_time: false

    amcl:
      ros__parameters:
        min_particles: 500
        max_particles: 2000
        alpha1: 0.2
        alpha2: 0.2
        alpha3: 0.2
        alpha4: 0.2
        alpha5: 0.2
        z_hit: 0.5
        z_short: 0.05
        z_max: 0.05
        z_rand: 0.5
        update_min_d: 0.2
        update_min_a: 0.2
        resample_interval: 1
        transform_tolerance: 1.0
        recovery_alpha_slow: 0.0
        recovery_alpha_fast: 0.0
        scan_topic: scan
        odom_frame_id: odom

    bt_navigator:
      ros__parameters:
        plugin_lib_names:
          - "nav2_compute_path_to_pose_action_bt_node"
          - "nav2_follow_path_action_bt_node"
          - "nav2_spin_action_bt_node"
          - "nav2_wait_action_bt_node"
          - "nav2_clear_costmap_service_bt_node"

    controller_server:
      ros__parameters:
        controller_plugins: ["FollowPath"]
        FollowPath:
          plugin: "nav2_core::FollowPath"
          min_speed: 0.1
          max_speed: 0.5

    planner_server:
      ros__parameters:
        planner_plugins: ["GridBased"]
        GridBased:
          plugin: "nav2_navfn_planner/NavfnPlanner"

    # 🔹 Fix Global Costmap Plugins
    global_costmap:
      ros__parameters:
        global_frame: map
        robot_base_frame: base_link
        update_frequency: 5.0
        publish_frequency: 2.0
        width: 10.0
        height: 10.0
        resolution: 0.05
        rolling_window: false
        track_unknown_space: true
        plugins: ["static_layer", "inflation_layer"]
        static_layer:
          plugin: "nav2_costmap_2d::StaticLayer"
        inflation_layer:
          plugin: "nav2_costmap_2d::InflationLayer"

    # 🔹 Fix Local Costmap Plugins
    local_costmap:
      ros__parameters:
        global_frame: odom
        robot_base_frame: base_link
        update_frequency: 10.0
        publish_frequency: 5.0
        width: 3.0
        height: 3.0
        resolution: 0.05
        rolling_window: true
        track_unknown_space: false
        plugins: ["obstacle_layer", "inflation_layer"]
        obstacle_layer:
          plugin: "nav2_costmap_2d::ObstacleLayer"
        inflation_layer:
          plugin: "nav2_costmap_2d::InflationLayer"
